### ISSUE TITLE
ft_calloc test says not_clean when including errno.h

### ISSUE THREAD

**Issue by steven42tokyo** [0x050f/libft-war-machine#39]
I'm including errno.h and setting errno = ENOMEM as per the calloc manpage.

Although in some cases malloc will do this for us and it's not necessary, my code checks for overflow after multiplying count and size as follows:

```
#include <stdlib.h>
#include "libft.h"
#include <errno.h>

void	*ft_calloc(size_t count, size_t size)
{
	size_t	total_count;
	void	*ptr;

	if (count == 0 || size == 0)
	{
		ptr = malloc(1);
		ft_bzero(ptr, 1);
		return (ptr);
	}
	total_count = count * size;
	if (total_count / count != size)
	{
		errno = ENOMEM;
		return (NULL);
	}
	ptr = malloc(total_count);
	if (ptr == NULL)
		return (NULL);
	ft_bzero(ptr, total_count);
	return (ptr);
}
```

**Comment by steven42tokyo** [comment]
I compared it with actual calloc and it seems that actual calloc does not throw ENOMEM.

#include <stdio.h>
int main ()
{
	char	*foo;

	errno = 0;
	foo = ft_calloc(184467440737095516, 8321713848);
	if (errno == ENOMEM)
		printf("overflow on ft_calloc\n");
	foo = calloc(184467440737095516, 8321713848);
	errno = 0;
	if (errno == ENOMEM)
		printf("overflow on calloc\n");
}

**Comment by AdrianSkar** [comment]
Hi! Noob here.
I think that might be because you're setting `errno = 0;` after calling calloc.
I get the print done if I remove that assignment and just do the `calloc` test.
