### ISSUE TITLE
Create seg fault at random test ...

### ISSUE THREAD

**Issue by Kosstraz** [0x050f/libft-war-machine#44]
Salut, quand je test certaines fonctions du style "is_digit" , "to_upper", ... bref des fonctions simples sans allocation de mémoire, et pourtant quand je les test il y a des seg fault qui apparaissent aléatoirement. Tout est bien setup. Merci d'avance

**Comment by 0x050f** [comment]
Salut,
Tu peux regarder la trace dans le fichier `deepthought`, peut-etre que ca te donnera + d'infos.

**Comment by Kosstraz** [comment]
Oui c'est ce que je fais, dans les traces du fichier `deepthought` il y a écrit qu'une seg fault est apparue pour des programmes telles que is_digit.c, is_alnum.c ... Ce qui n'a aucun sens à vrai dire. Mmhhh

**Comment by 0x050f** [comment]
Tu peux upload la trace ici ?

**Comment by 0x050f** [comment]
Should be fixed
