### ISSUE TITLE
Getting random test results when functions are correct

### ISSUE THREAD

**Issue by Artur-2k** [0x050f/libft-war-machine#46]
I followed your installation instructions and got it to run but the test results are not correct. They seem to be random 
Take this for example:
Run 1
![imagem](https://github.com/0x050f/libft-war-machine/assets/160274976/3b7a3f76-fbeb-4e97-b749-7cea9d61617c)
Run 2
![imagem](https://github.com/0x050f/libft-war-machine/assets/160274976/47274b79-e2ba-4785-9f3d-defc169cf3d1)
Trace
![imagem](https://github.com/0x050f/libft-war-machine/assets/160274976/2cbb236f-2560-4d00-980c-58ba2601ada9)
Src for the function in question. (Happens in almost every other function)
![imagem](https://github.com/0x050f/libft-war-machine/assets/160274976/90ef908b-bd5d-4af8-be96-d02d876b0ac4)

**Comment by 0x050f** [comment]
Should be fixed
